#!/usr/bin/python3
##
## EPITECH PROJECT, 2023
## 106bombyx
## File description:
## bunny population
##

import sys

def main():
	pass

if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        print(e, file=sys.stderr)
        exit(84)
